steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'functions',
         'deploy',
         '${_FUNC_GROUP}-update-metadata',
         '--project=${PROJECT_ID}',
         '--source=functions/update-metadata',
         '--memory=128MB',
         '--max-instances=200',
         '--entry-point=update_metadata',
         '--runtime=python37',
         '--trigger-topic=${_FUNC_GROUP}-update-metadata',
         '--update-env-vars=PROJECT_ID=${PROJECT_ID}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=func-group=${_FUNC_GROUP},task=database-import,functional-group=request-driven-db-import,inciting-action=request',
  ]
