steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'functions',
         'deploy',
         'trellis-update-metadata',
         '--project=${PROJECT_ID}',
         '--source=functions/update-metadata',
         '--memory=128MB',
         '--max-instances=200',
         '--entry-point=update_metadata',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=PROJECT_ID=${PROJECT_ID}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=user=trellis',
  ]
