steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'logging',
         'sinks',
         'delete',
         'wgs35-sink-insert-trellis-instance']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'logging',
         'sinks',
         'create',
         'wgs35-sink-insert-trellis-instance',
         'pubsub.googleapis.com/projects/gbsc-gcp-project-mvp-dev/topics/wgs35-log-insert-trellis-instance',
         '--log-filter', 'resource.type="gce_instance" AND protoPayload.serviceName="compute.googleapis.com" AND protoPayload.request."@type"="type.googleapis.com/compute.instances.insert" AND protoPayload.request.networkInterfaces.network:"networks/trellis-neo4j-dev" AND protoPayload.resourceName:"google-pipelines-worker" AND protoPayload.request.labels.key:"trellis-id"'
  ]
