steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         'trellis-postgres-insert-data',
         '--project=${PROJECT_ID}',
         '--source=functions/postgres-insert-data',
         '--memory=256MB',
         '--max-instances=20',
         '--entry-point=postgres_insert_data',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=user=trellis'
  ]
