name: gcf-{repo_owner}-trellis-{func_group}-create-blob-node-from-personalis-final
description: gcf-{func_group}-create-blob-node-from-personalis-final
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/create-blob-node/*
    - config/{data_group}/from-personalis/*
filename: functions/create-blob-node/cloudbuild.yaml
substitutions:
    _BUCKET_SHORT_NAME: from-personalis
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {trellis_bucket}
    _DATA_GROUP: {data_group}
    _FUNC_GROUP: {func_group}
    _ENVIRONMENT: google-cloud
    _OPERATION_SHORT_NAME: final
    _TRELLIS_BUCKET: {trellis_bucket}
    _TRIGGER_OPERATION: finalize
    _TRIGGER_RESOURCE: {project_id}-from-personalis
---
name: gcf-{repo_owner}-trellis-{func_group}-create-blob-node-from-personalis-meta
description: gcf-{func_group}-create-blob-node-from-personalis-meta
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/create-blob-node/*
    - config/{data_group}/from-personalis/*
filename: functions/create-blob-node/cloudbuild.yaml
substitutions:
    _BUCKET_SHORT_NAME: from-personalis
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {trellis_bucket}
    _DATA_GROUP: {data_group}
    _FUNC_GROUP: {func_group}
    _ENVIRONMENT: google-cloud
    _OPERATION_SHORT_NAME: meta
    _TRELLIS_BUCKET: {trellis_bucket}
    _TRIGGER_OPERATION: metadataUpdate
    _TRIGGER_RESOURCE: {project_id}-from-personalis
---
name: gcf-{repo_owner}-trellis-{func_group}-create-blob-node-from-{data_group}-final
description: gcf-{func_group}-create-blob-node-from-{data_group}-final
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/create-blob-node/*
    - config/{data_group}/from-personalis-{data_group}/*
filename: functions/create-blob-node/cloudbuild.yaml
substitutions:
    _BUCKET_SHORT_NAME: {data_group}
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {trellis_bucket}
    _DATA_GROUP: {data_group}
    _FUNC_GROUP: {func_group}
    _ENVIRONMENT: google-cloud
    _OPERATION_SHORT_NAME: final
    _TRELLIS_BUCKET: {trellis_bucket}
    _TRIGGER_OPERATION: finalize
    _TRIGGER_RESOURCE: {project_id}-from-personalis-{data_group}
---
name: gcf-{repo_owner}-trellis-{func_group}-create-blob-node-from-{data_group}-meta
description: gcf-{func_group}-create-blob-node-from-{data_group}-meta
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/create-blob-node/*
    - config/{data_group}/from-personalis-{data_group}/*
filename: functions/create-blob-node/cloudbuild.yaml
substitutions:
    _BUCKET_SHORT_NAME: {data_group}
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {trellis_bucket}
    _DATA_GROUP: {data_group}
    _FUNC_GROUP: {func_group}
    _ENVIRONMENT: google-cloud
    _OPERATION_SHORT_NAME: meta
    _TRELLIS_BUCKET: {trellis_bucket}
    _TRIGGER_OPERATION: metadataUpdate
    _TRIGGER_RESOURCE: {project_id}-from-personalis-{data_group}
