name: gcf-{repo_owner}-trellis-{func_group}-list-bucket-page
description: gcf-{func_group}-list-bucket-page
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/list-bucket-page/*
filename: functions/list-bucket-page/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{func_group}-match-blob-patterns
description: gcf-{func_group}-match-blob-patterns
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/match-blob-patterns/*
    - config/{data_group}/*
filename: functions/match-blob-patterns/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
    _TRIGGER_RESOURCE: {trellis_bucket}
---
name: gcf-{repo_owner}-trellis-{func_group}-db-query-index
description: gcf-{func_group}-db-query-index
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/db-query-index/*
filename: functions/db-query-index/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
    _TRIGGER_RESOURCE: {trellis_bucket}
---
name: gcf-{repo_owner}-trellis-{func_group}-update-metadata
description: gcf-{func_group}-update-metadata
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/update-metadata/*
filename: functions/update-metadata/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
