name: gcf-{repo_owner}-trellis-{func_group}-create-job-node
description: gcf-{func_group}-create-job-node
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/create-job-node/*
filename: functions/create-job-node/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{func_group}-triggers
description: gcf-{func_group}-triggers
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/check-triggers/*
    - config/{data_group}/{data_group}-triggers.py
filename: functions/check-triggers/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
    _TRIGGER_TOPIC: {func_group}-triggers
---
name: gcf-{repo_owner}-trellis-{func_group}-kill-job
description: gcf-{func_group}-kill-job
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/kill-job/*
filename: functions/kill-job/cloudbuild.yaml
substitutions:
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
    _TRIGGER_TOPIC: {func_group}-kill-job
---
name: gcf-{repo_owner}-trellis-{func_group}-db-query
description: gcf-{func_group}-db-query
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/db-query/*
filename: functions/db-query/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{func_group}-check-dstat
description: gcf-{func_group}-check-dstat
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/check-dstat/*
filename: functions/check-dstat/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
    _FUNCTION_NAME: {func_group}-check-dstat
