name: gcf-{repo_owner}-trellis-{func_group}-launch-gatk-5-dollar
description: gcf-{func_group}-launch-gatk-5-dollar
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/launch-gatk-5-dollar/*
filename: functions/launch-gatk-5-dollar/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{func_group}-fastq-to-ubam
description: gcf-{func_group}-fastq-to-ubam
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/launch-fastq-to-ubam/*
filename: functions/launch-fastq-to-ubam/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
