name: gcf-{repo_owner}-trellis-{data_group}-launch-bam-fastqc
description: gcf-{data_group}-launch-bam-fastqc
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/launch-bam-fastqc/*
filename: functions/launch-bam-fastqc/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{data_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud