name: gcf-{repo_owner}-trellis-{data_group}-launch-gatk-5-dollar
description: gcf-{data_group}-launch-gatk-5-dollar
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-gatk-5-dollar/*
filename: functions/launch-gatk-5-dollar/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: ***REMOVED***-dev-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{data_group}-fastq-to-ubam
description: gcf-{data_group}-fastq-to-ubam
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-fastq-to-ubam/*
filename: functions/launch-fastq-to-ubam/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: ***REMOVED***-dev-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud