name: trellis-{func_group}-sink-create-insert-trellis-worker
description: Create logging sink for Trellis workers.
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - logging-sinks/dev-build-triggers.yaml
    - logging-sinks/instance-insert-trellis-pipelines-worker/create-cloudbuild.yaml
filename: logging-sinks/instance-insert-trellis-pipelines-worker/create-cloudbuild.yaml
substitutions:
    _FUNC_GROUP: {func_group}
---
name: trellis-{func_group}-sink-update-insert-trellis-worker
description: Update logging sink for Trellis workers.
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - logging-sinks/dev-build-triggers.yaml
    - logging-sinks/instance-insert-trellis-pipelines-worker/update-cloudbuild.yaml
filename: logging-sinks/instance-insert-trellis-pipelines-worker/update-cloudbuild.yaml
substitutions:
    _FUNC_GROUP: {func_group}
---
name: trellis-{func_group}-sink-create-insert-cromwell-worker
description: Create logging sink for Cromwell workers.
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - logging-sinks/dev-build-triggers.yaml
    - logging-sinks/instance-insert-cromwell-pipelines-worker/create-cloudbuild.yaml
filename: logging-sinks/instance-insert-cromwell-pipelines-worker/create-cloudbuild.yaml
substitutions:
    _FUNC_GROUP: {func_group}
---
name: trellis-{func_group}-sink-update-insert-cromwell-worker
description: Update logging sink for Cromwell workers.
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - logging-sinks/dev-build-triggers.yaml
    - logging-sinks/instance-insert-cromwell-pipelines-worker/update-cloudbuild.yaml
filename: logging-sinks/instance-insert-cromwell-pipelines-worker/update-cloudbuild.yaml
substitutions:
    _FUNC_GROUP: {func_group}
---
name: trellis-{func_group}-sink-create-delete-pipelines-worker
description: Create logging sink for deleted workers.
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - logging-sinks/dev-build-triggers.yaml
    - logging-sinks/instance-delete-pipelines-worker/create-cloudbuild.yaml
filename: logging-sinks/instance-delete-pipelines-worker/create-cloudbuild.yaml
substitutions:
    _FUNC_GROUP: {func_group}
---
name: trellis-{func_group}-sink-update-delete-pipelines-worker
description: Update logging sink for deleted workers.
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - logging-sinks/dev-build-triggers.yaml
    - logging-sinks/instance-delete-pipelines-worker/update-cloudbuild.yaml
filename: logging-sinks/instance-delete-pipelines-worker/update-cloudbuild.yaml
substitutions:
    _FUNC_GROUP: {func_group}
