name: gcf-{repo_owner}-trellis-wgs35-launch-gatk-5-dollar
description: gcf-wgs35-launch-gatk-5-dollar
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-gatk-5-dollar/*
filename: functions/launch-gatk-5-dollar/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: gbsc-gcp-project-mvp-dev-trellis
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-wgs35-fastq-to-ubam
description: gcf-wgs35-fastq-to-ubam
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-fastq-to-ubam/*
filename: functions/launch-fastq-to-ubam/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: gbsc-gcp-project-mvp-dev-trellis
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud