name: gcf-{repo_owner}-trellis-{func_group}-launch-bam-fastqc
description: gcf-{func_group}-launch-bam-fastqc
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/launch-bam-fastqc/*
filename: functions/launch-bam-fastqc/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
    _TRIGGER_TOPIC: {func_group}-bam-fastqc
---
name: gcf-{repo_owner}-trellis-{func_group}-launch-flagstat
description: gcf-{func_group}-launch-flagstat
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/launch-flagstat/*
filename: functions/launch-flagstat/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
    _TRIGGER_TOPIC: {func_group}-flagstat
---
name: gcf-{repo_owner}-trellis-{func_group}-launch-vcfstats
description: gcf-{func_group}-launch-vcfstats
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/launch-vcfstats/*
filename: functions/launch-vcfstats/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _TRIGGER_TOPIC: {func_group}-vcfstats
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{func_group}-launch-text-to-table
description: gcf-{func_group}-launch-text-to-table
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/launch-text-to-table/*
filename: functions/launch-text-to-table/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _TRIGGER_TOPIC: {func_group}-text-to-table
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{func_group}-bigquery-import-csv
description: gcf-{func_group}-bigquery-import-csv
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/bigquery-import-csv/*
filename: functions/bigquery-import-csv/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _TRIGGER_TOPIC: {func_group}-bigquery-import-csv
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
