name: gcf-{repo_owner}-trellis-{func_group}-log-delete-instance
description: gcf-{func_group}-log-delete-instance
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/log-delete-instance/*
filename: functions/log-delete-instance/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{func_group}-log-insert-cromwell-instance
description: gcf-{func_group}-log-insert-cromwell-instance
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/log-insert-cromwell-instance/*
filename: functions/log-insert-cromwell-instance/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
---
name: gcf-{repo_owner}-trellis-{func_group}-log-insert-trellis-instance
description: gcf-{func_group}-log-insert-trellis-instance
github:
    owner: {repo_owner}
    name: {repo_name}
    push:
        branch: {branch_pattern}
included_files:
    - functions/log-insert-trellis-instance/*
filename: functions/log-insert-trellis-instance/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/{env}-{func_group}.yaml
    _CREDENTIALS_BUCKET: {project_id}-trellis
    _DATA_GROUP: {data_group}
    _ENVIRONMENT: google-cloud
