steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         '${_DATA_GROUP}-kill-duplicate-jobs',
         '--project=${PROJECT_ID}',
         '--source=functions/kill-duplicate-jobs',
         '--memory=128MB',
         '--max-instances=100',
         '--entry-point=kill_duplicate_jobs',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=PROJECT_ID=${PROJECT_ID}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=data-group=${_DATA_GROUP}',
         '--update-labels=task=kill-duplicate-jobs',
  ]
