steps:
- name: 'ubuntu'
  args: ['cp', '-r', 'config/${_DATA_GROUP}', 'functions/match-blob-patterns/']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'functions',
         'deploy',
         '${_DATA_GROUP}-match-blob-patterns',
         '--project=${PROJECT_ID}',
         '--source=functions/match-blob-patterns',
         '--memory=128MB',
         '--max-instances=100',
         '--entry-point=match_blob_patterns',
         '--runtime=python37',
         '--trigger-resource=${_TRIGGER_RESOURCE}',
         '--trigger-event=google.storage.object.finalize',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=data-group=${_DATA_GROUP},task=database-import,functional-group=request-driven-db-import,inciting-action=request',
  ]
