steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [
             'beta',
             'builds',
             'triggers',
             'import',
             'logging-sinks/build-triggers.yaml']
