steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         '${_FUNC_GROUP}-db-query',
         '--project=${PROJECT_ID}',
         '--source=functions/db-query',
         '--memory=256MB',
         '--max-instances=20',
         '--entry-point=query_db',
         '--runtime=python37',
         '--vpc-connector=trellis',
         '--trigger-topic=${_FUNC_GROUP}-db-queries',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=func-group=${_FUNC_GROUP}',
  ]
