steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         'wgs35-${_TRIGGER_TYPE}-triggers',
         '--project=${PROJECT_ID}',
         '--source=functions/check-triggers',
         '--memory=128MB',
         '--max-instances=200',
         '--entry-point=check_triggers',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_RESOURCE}',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=data-group=${_DATA_GROUP}',
  ]
