steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         'wgs35-check-node-triggers',
         '--project=${PROJECT_ID}',
         '--source=functions/check-node-triggers',
         '--memory=128MB',
         '--max-instances=100',
         '--entry-point=check_node_triggers',
         '--runtime=python37',
         '--trigger-resource=wgs35-new-node',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=data-group=wgs-35000',
  ]
