steps:
- name: 'ubuntu'
  args: ['ls', 'config/${_DATA_GROUP}']
- name: 'ubuntu'
  args: ['cp',
         'config/${_DATA_GROUP}/wgs35-triggers.py',
         'functions/check-triggers/']
- name: 'ubuntu'
  args: ['ls', 'functions/check-triggers']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         '${_DATA_GROUP}-triggers',
         '--project=${PROJECT_ID}',
         '--source=functions/check-triggers',
         '--memory=256MB',
         '--max-instances=20',
         '--entry-point=check_triggers',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=data-group=${_DATA_GROUP}',
  ]
