--- !DatabaseQuery
name: relateGenomeToFastq
cypher: "MATCH (fastq:Fastq)<-[]-(:PersonalisSequencing)<-[]-(s:Sample)<-[]-(:Person)-[]->(genome:Genome) WHERE s.sample = $sample AND NOT (genome)-[:HAS_SEQUENCING_READS]->(f) MERGE (genome)-[rel:HAS_SEQUENCING_READS]->(fastq) RETURN genome, rel, fastq" 
required_parameters:
  sample: str
write_transaction: true
split_results: false
publish_to: 
  - TOPIC_TRIGGERS
indexes:
  Sample: 
    - sample
returns:
  genome: node
  rel: relationship
  fastq: node
--- !DatabaseQuery
name: mergeBiologicalNodes
cypher: "MATCH (s:PersonalisSequencing) WHERE s.sample = $sample MERGE (s)<-[:WAS_USED_BY {ontology: 'provenance'}]-(:Sample {sample: s.sample})<-[:GENERATED {ontology:'provenance'}]-(:Person {sample: s.sample})-[:HAS_BIOLOGICAL_OME {ontology:'bioinformatics'}]->(genome:Genome {sample: s.sample}) RETURN genome"
required_parameters:
  sample: str
write_transaction: true
split_results: false
publish_to: 
  - TOPIC_TRIGGERS
indexes:
  Sample:
    - sample
returns:
  genome: node
--- !DatabaseQuery
name: relateFastqToPersonalisSequencing
cypher: "MATCH (seq:PersonalisSequencing), (fastq:Fastq) WHERE fastq.uri=$uri AND seq.sample=fastq.sample MERGE (seq)-[rel:GENERATED]->(fastq) RETURN seq, rel, fastq"
required_parameters:
  sample: str
  uri: str
write_transaction: true
split_results: false
publish_to: 
  - TOPIC_TRIGGERS
indexes:
  Fastq:
    - uri
  PersonalisSequencing:
    - sample
returns:
  pattern: relationship
  start: PersonalisSequencing
  relationship: GENERATED
  end: Fastq
--- !DatabaseQuery
name: relatePersonalisSequencingToFastqs
cypher: "MATCH (seq:PersonalisSequencing), (fastq:Fastq) WHERE seq.sample=$sample AND fastq.sample=seq.sample MERGE (seq)-[rel:GENERATED]->(fastq) RETURN seq, rel, fastq"
required_parameters:
  sample: str
write_transaction: true
split_results: false
publish_to: 
  - TOPIC_TRIGGERS
indexes:
  Fastq:
    - sample
  PersonalisSequencing:
    - sample
returns:
  pattern: relationship
  start: PersonalisSequencing
  relationship: GENERATED
  end: Fastq
--- !DatabaseQuery
name: relateMicroarrayToPersonalisSequencing
cypher: "MERGE (seq:PersonalisSequencing {sample: $sample}) WITH seq MATCH (microarray:Microarray) WHERE microarray.uri=$uri MERGE (seq)-[rel:GENERATED]->(micro) RETURN seq, rel, microarray"
required_parameters:
  Microarray:
    - uri
  PersonalisSequencing:
    - sample
write_transaction: true
split_results: false
publish_to: 
  - TOPIC_TRIGGERS
returns:
  seq: node
  rel: relationship
  microarray: node
--- !DatabaseQuery
name: relateChecksumToPersonalisSequencing
cypher: "MERGE (seq:PersonalisSequencing {sample: $sample}) WITH seq MATCH (checksum:Checksum) WHERE checksum.uri=$uri MERGE (seq)-[rel:GENERATED]->(checksum) RETURN seq, rel, checksum"
required_parameters:
  Checksum:
    - uri
  PersonalisSequencing:
    - sample
write_transaction: true
split_results: false
publish_to: 
  - TOPIC_TRIGGERS
returns:
  seq: node
  rel: relationship
  checksum: node