name: gcf-StanfordBioinformatics-trellis-wgs35-list-bucket-page
description: gcf-wgs35-list-bucket-page
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-
included_files:
    - functions/list-bucket-page/*
filename: functions/list-bucket-page/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: ***REMOVED***-dev-trellis
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud
---
name: gcf-StanfordBioinformatics-trellis-wgs35-match-blob-patterns
description: gcf-wgs35-match-blob-patterns
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-
included_files:
    - functions/match-blob-patterns/*
    - config/wgs35/*
filename: functions/match-blob-patterns/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: ***REMOVED***-dev-trellis
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud
    _TRIGGER_RESOURCE: ***REMOVED***-dev-trellis
---
name: gcf-StanfordBioinformatics-trellis-wgs35-db-query-index
description: gcf-wgs35-db-query-index
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-
included_files:
    - functions/db-query-index/*
filename: functions/db-query-index/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: ***REMOVED***-dev-trellis
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud
    _TRIGGER_RESOURCE: ***REMOVED***-dev-trellis
---
name: gcf-StanfordBioinformatics-trellis-wgs35-update-metadata
description: gcf-wgs35-update-metadata
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-
included_files:
    - functions/update-metadata/*
filename: functions/update-metadata/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: ***REMOVED***-dev-trellis
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud
