name: gcf-StanfordBioinformatics-trellis-wgs35-launch-bam-fastqc
description: gcf-wgs35-launch-bam-fastqc
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-bam-fastqc/*
filename: functions/launch-bam-fastqc/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: gbsc-gcp-project-mvp-dev-trellis
    _TRIGGER_TOPIC: wgs35-bam-fastqc
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud
---
name: gcf-StanfordBioinformatics-trellis-wgs35-launch-flagstat
description: gcf-wgs35-launch-flagstat
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-flagstat/*
filename: functions/launch-flagstat/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: gbsc-gcp-project-mvp-dev-trellis
    _TRIGGER_TOPIC: wgs35-flagstat
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud
---
name: gcf-StanfordBioinformatics-trellis-wgs35-launch-vcfstats
description: gcf-wgs35-launch-vcfstats
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-vcfstats/*
filename: functions/launch-vcfstats/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: gbsc-gcp-project-mvp-dev-trellis
    _TRIGGER_TOPIC: wgs35-vcfstats
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud