steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'functions',
         'deploy',
         '${_DATA_GROUP}-db-query-index',
         '--project=${PROJECT_ID}',
         '--source=functions/db-query-index',
         '--memory=128MB',
         '--max-instances=10',
         '--entry-point=query_db_index',
         '--runtime=python37',
         '--trigger-resource=${_TRIGGER_RESOURCE}',
         '--trigger-event=google.storage.object.finalize',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=data-group=${_DATA_GROUP},task=database-import,functional-group=request-driven-db-import,inciting-actions=request',
  ]
