steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         '${_FUNC_GROUP}-list-bucket-page',
         '--project=${PROJECT_ID}',
         '--source=functions/list-bucket-page',
         '--memory=128MB',
         '--max-instances=100',
         '--entry-point=list_bucket_page',
         '--runtime=python37',
         '--trigger-topic=${_FUNC_GROUP}-list-bucket-page',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=func-group=${_FUNC_GROUP},task=database-import,inciting-action=request,functional-group=request-driven-db-import',
  ]
