name: gcf-subio-trellis-wgs35-launch-gatk-5-dollar
description: gcf-wgs35-launch-gatk-5-dollar
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-gatk-5-dollar/*
filename: functions/launch-gatk-5-dollar/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: gbsc-gcp-project-mvp-dev-trellis
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud
---
name: gcf-subio-trellis-wgs35-fastq-to-ubam
description: gcf-wgs35-fastq-to-ubam
github:
    owner: StanfordBioinformatics
    name: trellis-mvp-wgs-35000
    push:
        branch: develop|feat-*
included_files:
    - functions/launch-fastq-to-ubam/*
filename: functions/launch-fastq-to-ubam/cloudbuild.yaml
substitutions:
    _CREDENTIALS_BLOB: credentials/dev-wgs35.yaml
    _CREDENTIALS_BUCKET: gbsc-gcp-project-mvp-dev-trellis
    _DATA_GROUP: wgs35
    _ENVIRONMENT: google-cloud