steps:
- name: 'ubuntu'
  args: ['cp', '-r', 'config/wgs35', 'functions/create-node/']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         '${_DATA_GROUP}-create-node-${_BUCKET_SHORT_NAME}-${_OPERATION_SHORT_NAME}',
         '--project=${PROJECT_ID}',
         '--source=functions/create-node',
         '--memory=128MB',
         '--max-instances=100',
         '--entry-point=create_node_query',
         '--runtime=python37',
         '--trigger-resource=${_TRIGGER_RESOURCE}',
         '--trigger-event=google.storage.object.${_TRIGGER_OPERATION}',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-env-vars=TRIGGER_OPERATION=${_TRIGGER_OPERATION}',
         '--update-labels=data-group=${_DATA_GROUP}',
         '--update-labels=trigger-operation=${_OPERATION_SHORT_NAME}',
         '--update-labels=trigger-resource=${_TRIGGER_RESOURCE}'
  ]
