steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         '${_FUNC_GROUP}-kill-job',
         '--project=${PROJECT_ID}',
         '--source=functions/kill-job',
         '--memory=128MB',
         '--max-instances=40',
         '--timeout=60',
         '--entry-point=kill_job',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=PROJECT_ID=${PROJECT_ID}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-labels=func-group=${_FUNC_GROUP}',
         '--update-labels=task=kill-job',
  ]
