steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
         'beta',
         'functions',
         'deploy',
         'trellis-launch-extract-mapped-reads',
         '--project=${PROJECT_ID}',
         '--source=functions/launch-extract-mapped-reads',
         '--memory=128MB',
         '--max-instances=20',
         '--entry-point=launch_extract_mapped_reads',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         # Fix for logging issue: https://issuetracker.google.com/issues/155215191#comment112
         '--update-env-vars=USE_WORKER_V2=true',
         '--update-env-vars=PYTHON37_DRAIN_LOGS_ON_CRASH_WAIT_SEC=5',
         '--update-labels=user=trellis',
  ]
